Bugfix: index expects default export
For me, e.g. `omit` is broken:
> TypeError: (0 , _composers.keyIn) is not a function
The reason seems to be, that the local index here expects a default export of `keyIn.